<a href="https://colab.research.google.com/github/ngwalker93/ADS-507-Final-Team-Project/blob/main/ADS507_Final_FDA_Shortage.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ADS 507 Final Team Project 

## FDA Drug Shortage Analysis Pipeline

### Team 1 : Sheshma Jaganathan, Mark Henry Villanueva, and Nancy Walker

## Introduction 

The Goal of this project is to build a MySQL-based data pipeline that combines the FDA datasets (National Drug Code database and Drug Shortages) for analysis. 

Questions: 


    Which manufacturers have the highest shortage risk?

    Do branded drugs have longer shortage durations than generics?

    Which package types are most vulnerable to shortages?

This file is used for pipeline exploration.

## National Drug Code Database

Download, explore, and transform

In [1]:
# Import necessary libraries

import pandas as pd
import requests
import zipfile
import io
import os
import json

url = "https://download.open.fda.gov/drug/ndc/drug-ndc-0001-of-0001.json.zip"

# Download the file
response = requests.get(url)
response.raise_for_status()

zip_bytes = io.BytesIO(response.content)

with zipfile.ZipFile(zip_bytes) as z:
    z.extractall("data")

json_path = "data/drug-ndc-0001-of-0001.json"

# Load JSON file first, then extract the results
with open(json_path, 'r') as f:
    data = json.load(f)

# The actual drug data is in the 'results' key
df = pd.DataFrame(data['results'])

df.head()

,product_ndc,generic_name,labeler_name,brand_name,active_ingredients,finished,packaging,listing_expiration_date,openfda,marketing_category,...,product_type,route,marketing_start_date,product_id,brand_name_base,brand_name_suffix,pharm_class,application_number,marketing_end_date,dea_schedule
0,76472-1150,LACHESIS MUTA VENOM,SEVENE USA,Lachesis Mutus,"[{'name': 'LACHESIS MUTA VENOM', 'strength': '...",True,"[{'package_ndc': '76472-1150-1', 'description'...",20261231,"{'manufacturer_name': ['SEVENE USA'], 'spl_set...",UNAPPROVED HOMEOPATHIC,...,HUMAN OTC DRUG,[SUBLINGUAL],20111130,76472-1150_35b75182-a5fb-1d2d-e063-6394a90ac78d,Lachesis Mutus,NaN,NaN,NaN,NaN,NaN
1,76472-1158,PULSATILLA VULGARIS,SEVENE USA,Pulsatilla,"[{'name': 'PULSATILLA VULGARIS', 'strength': '...",True,"[{'package_ndc': '76472-1158-1', 'description'...",20261231,"{'manufacturer_name': ['SEVENE USA'], 'spl_set...",UNAPPROVED HOMEOPATHIC,...,HUMAN OTC DRUG,[SUBLINGUAL],20111130,76472-1158_103136e3-e773-f739-e063-6294a90aea02,Pulsatilla,NaN,NaN,NaN,NaN,NaN
2,76472-3006,SODIUM BORATE,SEVENE USA,Borax 200ck,"[{'name': 'SODIUM BORATE', 'strength': '200 [k...",True,"[{'package_ndc': '76472-3006-1', 'description'...",20261231,"{'manufacturer_name': ['SEVENE USA'], 'spl_set...",UNAPPROVED HOMEOPATHIC,...,HUMAN OTC DRUG,[SUBLINGUAL],20111130,76472-3006_2dcc6b58-7a86-e2ac-e063-6294a90a9262,Borax,200ck,NaN,NaN,NaN,NaN
3,76472-3025,Mercurius Solubilis,SEVENE USA,Mercurius Solubilis 200ck,"[{'name': 'MERCURIUS SOLUBILIS', 'strength': '...",True,"[{'package_ndc': '76472-3025-1', 'description'...",20261231,"{'manufacturer_name': ['SEVENE USA'], 'spl_set...",UNAPPROVED HOMEOPATHIC,...,HUMAN OTC DRUG,[SUBLINGUAL],20111123,76472-3025_2ddc5704-a4b5-6b23-e063-6294a90ace59,Mercurius Solubilis,200ck,NaN,NaN,NaN,NaN
4,76472-3029,PHYTOLACCA DECANDRA,SEVENE USA,PHYTOLACCA DECANDRA 200ck,"[{'name': 'PHYTOLACCA AMERICANA ROOT', 'streng...",True,"[{'package_ndc': '76472-3029-1', 'description'...",20261231,"{'manufacturer_name': ['SEVENE USA'], 'spl_set...",UNAPPROVED HOMEOPATHIC,...,HUMAN OTC DRUG,[SUBLINGUAL],20111123,76472-3029_2dcc6dde-9cf3-d960-e063-6294a90aab92,PHYTOLACCA DECANDRA,200ck,NaN,NaN,NaN,NaN

In [2]:
# List all column names in the raw NDC dataset

df.columns.tolist()

['product_ndc',
 'generic_name',
 'labeler_name',
 'brand_name',
 'active_ingredients',
 'finished',
 'packaging',
 'listing_expiration_date',
 'openfda',
 'marketing_category',
 'dosage_form',
 'spl_id',
 'product_type',
 'route',
 'marketing_start_date',
 'product_id',
 'brand_name_base',
 'brand_name_suffix',
 'pharm_class',
 'application_number',
 'marketing_end_date',
 'dea_schedule']

In [3]:
# Column data types
df.dtypes

product_ndc                object
generic_name               object
labeler_name               object
brand_name                 object
active_ingredients         object
finished                     bool
packaging                  object
listing_expiration_date    object
openfda                    object
marketing_category         object
dosage_form                object
spl_id                     object
product_type               object
route                      object
marketing_start_date       object
product_id                 object
brand_name_base            object
brand_name_suffix          object
pharm_class                object
application_number         object
marketing_end_date         object
dea_schedule               object
dtype: object

In [4]:
# Check the 'marketing_start_date' and 'marketing_end_date' columns format
for c in ["marketing_start_date", "marketing_end_date"]:
    print("\n", c)
    print(df[c].dtype)
    print(df[c].head(10).tolist())
    print(df[c].astype("string").str.strip().value_counts(dropna=False).head(3))

 marketing_start_date
object
['20111130', '20111130', '20111130', '20111123', '20111123', '20111123', '20220708', '20220708', '20230626', '20230626']
marketing_start_date
19830303    1763
19810915    1291
20150101     676
Name: count, dtype: Int64

 marketing_end_date
object
[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
marketing_end_date
<NA>        126704
20260228       223
20261231       223
Name: count, dtype: Int64

In [5]:
# Standardize raw FDA field names into ISO-8601 formate to facilitate downstream processing. 
# Ensures dates fields are loaded as native DATE in MySQL 
date_cols = ['listing_expiration_date', 'marketing_start_date', 'marketing_end_date']

def yyyymmdd_to_iso(series: pd.Series) -> pd.Series:
    s = series.astype("string").str.strip()

    # normalize missing/placeholder values to NaT
    s = s.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA,
        "None": pd.NA, "null": pd.NA, "NULL": pd.NA,
        "0": pd.NA, "00000000": pd.NA})
    
    # parse YYYYMMDD to date 
    dt = pd.to_datetime(s, format="%Y%m%d", errors="coerce")

    # Return ISO string for MySQL/CSV: "YYYY-MM-DD" (or <NA> for missing)
    return dt.dt.strftime("%Y-%m-%d").astype("string")

for col in date_cols:
    df[col] = yyyymmdd_to_iso(df[col])

# Verify date conversion
for c in date_cols:
    print("\n", c)
    print(df[c].dtype)
    print(df[c].head(10).tolist())
    print(df[c].value_counts(dropna=False).head(3))

 listing_expiration_date
string
['2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31', '2026-12-31']
listing_expiration_date
2026-12-31    115952
2027-12-31     10747
<NA>            4379
Name: count, dtype: Int64

 marketing_start_date
string
['2011-11-30', '2011-11-30', '2011-11-30', '2011-11-23', '2011-11-23', '2011-11-23', '2022-07-08', '2022-07-08', '2023-06-26', '2023-06-26']
marketing_start_date
1983-03-03    1763
1981-09-15    1291
2015-01-01     676
Name: count, dtype: Int64

 marketing_end_date
string
[<NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, <NA>]
marketing_end_date
<NA>          126704
2026-02-28       223
2026-12-31       223
Name: count, dtype: Int64

### Inspect Nested NDC Fields

In [6]:
# Packaging Field inspection
df.loc[df["packaging"].notna(), "packaging"].iloc[0]

[{'package_ndc': '76472-1150-1',
  'description': '80 PELLET in 1 CYLINDER (76472-1150-1)',
  'marketing_start_date': '20111130',
  'sample': False}]

packaging is a list of dicts including package_ndc, description, marketing_start_date, and sample. THis is a one-to-many relationship with the main drug table. This column can be separated out into its own table. 

Foreign key: product_ndc

In [7]:
# Check dictionary keys used in 'packaging' field
keys = set()
for lst in df.loc[df["packaging"].notna(), "packaging"].head(500):
    for d in (lst if isinstance(lst, list) else []):
        if isinstance(d, dict):
            keys.update(d.keys())
sorted(keys)

['description',
 'marketing_end_date',
 'marketing_start_date',
 'package_ndc',
 'sample']

In [8]:
# Create a one-to-many packaging table linked by product_ndc

packaging_rows = []

for _, row in df[["product_ndc", "packaging"]].dropna().iterrows():
    for pkg in row["packaging"]:
        pkg_row = {
            "product_ndc": row["product_ndc"],
            "package_ndc": pkg.get("package_ndc"),
            "description": pkg.get("description"),
            "marketing_start_date": pkg.get("marketing_start_date"),
            "marketing_end_date": pkg.get("marketing_end_date"),
            "sample": pkg.get("sample"),
        }
        packaging_rows.append(pkg_row)

# Build packaging DataFrame
ndc_packaging = pd.DataFrame(packaging_rows)

# normalize packaging-level dates to YYYY-MM-DD strings for MySQL DATE
for col in ["marketing_start_date", "marketing_end_date"]:
    if col in ndc_packaging.columns:
        ndc_packaging[col] = pd.to_datetime(
            ndc_packaging[col].astype("string").str.strip().str.replace(r"\.0$", "", regex=True),
            format="%Y%m%d",
            errors="coerce"
        ).dt.strftime("%Y-%m-%d").astype("string")

# ensure boolean "sample' column is boolean (and MySQL-friendly later)
if "sample" in ndc_packaging.columns:
    ndc_packaging["sample"] = (
    ndc_packaging["sample"]
        .fillna(False)
        .infer_objects(copy=False)
        .astype(bool))

ndc_packaging.head()

/var/folders/4d/9t08wrpn3gvcfr0wtwc31yx80000gn/T/ipykernel_25664/2918935697.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .fillna(False)

,product_ndc,package_ndc,description,marketing_start_date,marketing_end_date,sample
0,76472-1150,76472-1150-1,80 PELLET in 1 CYLINDER (76472-1150-1),2011-11-30,<NA>,False
1,76472-1158,76472-1158-1,80 PELLET in 1 CYLINDER (76472-1158-1),2011-11-30,<NA>,False
2,76472-3006,76472-3006-1,80 PELLET in 1 CYLINDER (76472-3006-1),2011-11-30,<NA>,False
3,76472-3025,76472-3025-1,80 PELLET in 1 CYLINDER (76472-3025-1),2011-11-23,<NA>,False
4,76472-3029,76472-3029-1,80 PELLET in 1 CYLINDER (76472-3029-1),2011-11-23,<NA>,False

In [9]:
# Active Ingredients Field inspection
df.loc[df["active_ingredients"].notna(), "active_ingredients"].iloc[0]

[{'name': 'LACHESIS MUTA VENOM', 'strength': '30 [hp_C]/1'}]

In [10]:
keys = set()
for lst in df.loc[df["active_ingredients"].notna(), "active_ingredients"].head(500):
    for d in (lst if isinstance(lst, list) else []):
        if isinstance(d, dict):
            keys.update(d.keys())
sorted(keys)

['name', 'strength']

Active ingredients is also a list of dictionaries including name and strenght. This can also be separated out into its own table. 

Foreign key: product_ndc

In [11]:
active_rows = []

for _, row in df[["product_ndc", "active_ingredients"]].dropna().iterrows():
    for ing in row["active_ingredients"]:
        active_rows.append({
            "product_ndc": row["product_ndc"],
            "name": ing.get("name"),
            "strength": ing.get("strength"),})

# Build active ingredients DataFrame
ndc_active_ingredients = pd.DataFrame(active_rows)
ndc_active_ingredients.head()

  product_ndc                       name      strength
0  76472-1150        LACHESIS MUTA VENOM   30 [hp_C]/1
1  76472-1158        PULSATILLA VULGARIS   30 [hp_C]/1
2  76472-3006              SODIUM BORATE  200 [kp_C]/1
3  76472-3025        MERCURIUS SOLUBILIS  200 [kp_C]/1
4  76472-3029  PHYTOLACCA AMERICANA ROOT  200 [kp_C]/1

In [12]:
# OpenFDA Field inspection
df.loc[df["openfda"].notna(), "openfda"].iloc[0]

{'manufacturer_name': ['SEVENE USA'],
 'spl_set_id': ['cf7139b1-1741-4d03-ab79-559924076682'],
 'is_original_packager': [True],
 'upc': ['0855717003369'],
 'unii': ['VSW71SS07I']}

OpenFDA is a dictionary of string values. It can be separated into it's own reference table. It includes metadata about the product. Useful for join NDC → openfda → RxCUI / UNII lookups, manufacturer analyse, and matching shortages to standardized identifiers. 

Foreign key: product_ndc

In [13]:
# Inspect the keys 
keys = set()
for d in df.loc[df["openfda"].notna(), "openfda"].head(1000):
    if isinstance(d, dict):
        keys.update(d.keys())
sorted(keys)

['is_original_packager',
 'manufacturer_name',
 'nui',
 'pharm_class_cs',
 'pharm_class_epc',
 'pharm_class_moa',
 'pharm_class_pe',
 'rxcui',
 'spl_set_id',
 'unii',
 'upc']

In [14]:
# Transform openfda field into a separate one-to-one table
openfda_rows = []

for _, row in df[["product_ndc", "openfda"]].dropna().iterrows():
    d = row["openfda"]
    if not isinstance(d, dict):
        continue

    flat = {"product_ndc": row["product_ndc"]}

    for k, v in d.items():
        # most values are lists; keep first element
        if isinstance(v, list):
            flat[k] = v[0] if len(v) > 0 else None
        else:
            flat[k] = v

    openfda_rows.append(flat)

ndc_openfda = pd.DataFrame(openfda_rows)

# clean strings
for c in ndc_openfda.columns:
    if c != "product_ndc":
        ndc_openfda[c] = ndc_openfda[c].astype("string").str.strip()

ndc_openfda.head()

,product_ndc,manufacturer_name,spl_set_id,is_original_packager,upc,unii,nui,pharm_class_cs,pharm_class_epc,pharm_class_pe,rxcui,pharm_class_moa
0,76472-1150,SEVENE USA,cf7139b1-1741-4d03-ab79-559924076682,True,0855717003369,VSW71SS07I,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,76472-1158,SEVENE USA,50113409-0228-4403-aded-92e72e220aa7,True,0855717003093,I76KB35JEV,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,76472-3006,SEVENE USA,c8d359b2-3ba0-3117-e053-2a95a90aac2f,True,0850022941252,91MBZ8H3QO,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,76472-3025,SEVENE USA,cf890d83-ac5b-29df-e053-2995a90a6211,True,0810095311444,324Y4038G2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,76472-3029,SEVENE USA,cf892285-4d72-3937-e053-2995a90a337e,True,0810095311482,11E6VI8VEG,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [15]:
# Create a clean, flat core NDC products table to serve as the primary
# reference table for joining with FDA drug shortage data.
# This table keeps only one-to-one product attributes (no nested fields).

ndc_core_cols = [
    "product_ndc",              # Primary identifier / join key
    "brand_name",
    "generic_name",
    "labeler_name",
    "product_type",
    "marketing_category",
    "dosage_form",
    "route",
    "finished",
    "listing_expiration_date",
    "marketing_start_date",
    "marketing_end_date",
    "application_number",
    "pharm_class",
    "dea_schedule"
]

ndc_products = df[ndc_core_cols].copy()

ndc_products.head()

,product_ndc,brand_name,generic_name,labeler_name,product_type,marketing_category,dosage_form,route,finished,listing_expiration_date,marketing_start_date,marketing_end_date,application_number,pharm_class,dea_schedule
0,76472-1150,Lachesis Mutus,LACHESIS MUTA VENOM,SEVENE USA,HUMAN OTC DRUG,UNAPPROVED HOMEOPATHIC,PELLET,[SUBLINGUAL],True,2026-12-31,2011-11-30,<NA>,NaN,NaN,NaN
1,76472-1158,Pulsatilla,PULSATILLA VULGARIS,SEVENE USA,HUMAN OTC DRUG,UNAPPROVED HOMEOPATHIC,PELLET,[SUBLINGUAL],True,2026-12-31,2011-11-30,<NA>,NaN,NaN,NaN
2,76472-3006,Borax 200ck,SODIUM BORATE,SEVENE USA,HUMAN OTC DRUG,UNAPPROVED HOMEOPATHIC,PELLET,[SUBLINGUAL],True,2026-12-31,2011-11-30,<NA>,NaN,NaN,NaN
3,76472-3025,Mercurius Solubilis 200ck,Mercurius Solubilis,SEVENE USA,HUMAN OTC DRUG,UNAPPROVED HOMEOPATHIC,PELLET,[SUBLINGUAL],True,2026-12-31,2011-11-23,<NA>,NaN,NaN,NaN
4,76472-3029,PHYTOLACCA DECANDRA 200ck,PHYTOLACCA DECANDRA,SEVENE USA,HUMAN OTC DRUG,UNAPPROVED HOMEOPATHIC,PELLET,[SUBLINGUAL],True,2026-12-31,2011-11-23,<NA>,NaN,NaN,NaN

Note: Missing values appear as either NaN or <NA> depending on pandas dtype inference. Since both serialize to SQL NULL during loading, no correction is required for MySQL.

In [16]:
# Confirm how many rows and columns are in the core NDC table

ndc_products.shape

(131081, 15)

In [17]:
# Show the proportion of missing values for each column in the core NDC table

ndc_products.isna().mean().sort_values(ascending=False)

marketing_end_date         0.966608
dea_schedule               0.952480
pharm_class                0.455260
application_number         0.277927
route                      0.170681
brand_name                 0.157406
listing_expiration_date    0.033407
generic_name               0.000023
product_ndc                0.000000
labeler_name               0.000000
product_type               0.000000
marketing_category         0.000000
dosage_form                0.000000
finished                   0.000000
marketing_start_date       0.000000
dtype: float64

In [18]:
# Confirm multiple packaging records exist per product_ndc

ndc_packaging.groupby("product_ndc").size().sort_values(ascending=False).head()

product_ndc
59579-002    63
84165-016    59
84165-102    58
84165-006    55
84165-002    54
dtype: int64

One product can have many packages. Many rows per product exist.

In [19]:
# rename ingredient name column for clarity
ndc_active_ingredients = ndc_active_ingredients.rename(columns={"name": "ingredient_name"})
# Confirm multiple active ingredient records exist per product_ndc
ndc_active_ingredients.duplicated(subset=["product_ndc", "ingredient_name"]).sum()

np.int64(2613)

In [20]:
# Confirm multiple active ingredient records exist per product_ndc
ndc_active_ingredients.groupby("product_ndc").size().sort_values(ascending=False).head()

product_ndc
62713-969    102
62713-968    102
62713-959    102
62713-958    102
62713-975    101
dtype: int64

Active ingredients were modeled as a one-to-many child table. Cardinality checks confirmed multiple ingredient records per product, and duplicate product–ingredient combinations were validated to ensure relational integrity

In [21]:
# Confirm one-to-one relationship in openfda table
ndc_openfda.groupby("product_ndc").size().value_counts()

1     126954
2       1584
3        156
4         56
6         11
5          5
9          3
8          2
10         2
7          2
13         1
17         1
22         1
36         1
11         1
Name: count, dtype: int64

openfda is NOT strictly one-to-one with product_ndc in the data.
There are multiple identifiers per product. 

Collapse to one row per product

In [22]:
# Collapse openfda table into one row per product_ndc by keeping the first non-null value for each column
ndc_openfda_collapsed = (
    ndc_openfda
      .groupby("product_ndc", as_index=False)
      .agg({
          "manufacturer_name": lambda x: "|".join(sorted(set(x.dropna()))),
          "rxcui": lambda x: "|".join(sorted(set(x.dropna()))),
          "spl_set_id": lambda x: "|".join(sorted(set(x.dropna()))),
          "upc": lambda x: "|".join(sorted(set(x.dropna()))),
          "unii": lambda x: "|".join(sorted(set(x.dropna()))),
      })
)
ndc_openfda_collapsed.head(20)

,product_ndc,manufacturer_name,rxcui,spl_set_id,upc,unii
0,0002-0013,,,,,
1,0002-0095,,,,,
2,0002-0096,,,,,
3,0002-0113,,,,,
4,0002-0119,,,,,
5,0002-0121,,,,,
6,0002-0124,,,,,
7,0002-0137,,,,,
8,0002-0152,Eli Lilly and Company,,487cd7e7-434c-4925-99fa-aa80b1cc776b,0300022002045,OYN3CCI6QE
9,0002-0213,Eli Lilly and Company,311034,b519bd83-038c-4ec5-a231-a51ec5cc291f,0300028215012,1Y17CTI5SR
10,0002-0243,Eli Lilly and Company,,487cd7e7-434c-4925-99fa-aa80b1cc776b,0300022002045,OYN3CCI6QE
11,0002-0485,,,,,
12,0002-0535,,,,,
13,0002-0770,,,,,
14,0002-0800,Eli Lilly and Company,242120,c8ecbd7a-0e22-4fc7-a503-faa58c1b6f3f,,059QF0KO0R
15,0002-0872,,,,,
16,0002-1076,,,,,
17,0002-1099,,,,,
18,0002-1152,Eli Lilly and Company,2601743,d2d7da5d-ad07-4228-955f-cf7e355c8cc0,0300023002013,OYN3CCI6QE
19,0002-1200,Eli Lilly and Company,,bb5a5043-0f51-11df-8a39-0800200c9a66,,6W15Z5R0RU

In [23]:
# Confirm one-to-one relationship in collapsed openfda table
ndc_openfda_collapsed.groupby("product_ndc").size().value_counts()

1    128780
Name: count, dtype: int64

OpenFDA is stored in a curated, one-row-per-product table to support reliable joins

Although the NDC dataset contains an openfda enrichment object, its identifiers are sparse and primarily intended for cross-endpoint linkage, which is outside the scope of this project’s shortage-focused analysis. Will Keep it as a filtered enrichment table that includes only rows where at least one openfda field exists. It is not used in joins for core analysis and analytical logic is not built around it.

In [24]:
# Save reduced tables locally for reuse in later steps

ndc_products.to_csv("data/ndc_products.csv", index=False)
ndc_packaging.to_csv("data/ndc_packaging.csv", index=False)
ndc_active_ingredients.to_csv("data/ndc_active_ingredients.csv", index=False)
ndc_openfda_collapsed.to_csv("data/ndc_openfda_collapsed.csv", index=False, na_rep="")

## Shortages Dataset 

Download, explore, and transform

In [25]:
# URL for the openFDA drug shortages dataset
shortages_url = "https://download.open.fda.gov/drug/shortages/drug-shortages-0001-of-0001.json.zip"

# Download the file
response = requests.get(shortages_url)
response.raise_for_status()

zip_bytes = io.BytesIO(response.content)

with zipfile.ZipFile(zip_bytes) as z:
    z.extractall("data")

shortages_json_path = "data/drug-shortages-0001-of-0001.json"

# Load JSON and extract the actual records from 'results'
with open(shortages_json_path, "r") as f:
    shortages_data = json.load(f)

shortage_df = pd.DataFrame(shortages_data["results"])

shortage_df.head()

,update_type,initial_posting_date,package_ndc,generic_name,contact_info,availability,openfda,update_date,therapeutic_category,dosage_form,presentation,company_name,status,related_info,discontinued_date,shortage_reason,change_date,related_info_link,resolved_note
0,Revised,10/12/2022,0555-0971-02,"Amphetamine Aspartate Monohydrate, Amphetamine...",800-545-8800,Available,"{'application_number': ['ANDA040422'], 'brand_...",02/02/2026,[Psychiatry],Tablet,"Dextroamphetamine Saccharate, Amphetamine Aspa...","Teva Pharmaceuticals USA, Inc.",Current,NaN,NaN,NaN,NaN,NaN,NaN
1,Reverified,03/23/2018,63323-285-61,Ropivacaine Hydrochloride Injection,888-386-1300,Unavailable,"{'application_number': ['NDA020533'], 'brand_n...",02/05/2026,[Anesthesia],Injection,"Naropin, Injection, 2 mg/1 mL (NDC 63323-285-61)","Fresenius Kabi USA, LLC",Current,Next release not available at this time.,NaN,NaN,NaN,NaN,NaN
2,New,11/07/2025,0409-4911-34,Atropine Sulfate Injection,844-646-4398,NaN,NaN,11/07/2025,"[Anesthesia, Neurology, Pediatric]",Injection,"Atropine Sulfate, Injection, (Adult)1 mg/10 mL...","Hospira, Inc., a Pfizer Company",To Be Discontinued,Discontinuation of the manufacture of the drug,11/07/2025,NaN,NaN,NaN,NaN
3,New,02/03/2016,0641-6262-01,Sodium Acetate Injection,800-631-2174,Available,"{'application_number': ['ANDA216920'], 'brand_...",12/22/2025,"[Endocrinology/Metabolism, Gastroenterology, P...",Injection,"Sodium Acetate, Injection, 100 mEq/50mL (2 mEq...","Hikma Pharmaceuticals USA, Inc.",Current,NaN,NaN,NaN,NaN,NaN,NaN
4,Revised,04/28/2023,60505-6282-7,Carboplatin Injection,Apotex Inc.: 800-706-5575,Limited Availability,"{'application_number': ['ANDA077861'], 'brand_...",01/15/2026,[Oncology],Injection,"Carboplatin, Injection, 600 mg/60 mL (10 mg/mL...",Teyro Labs,Current,Discontinuation of the manufacture of the drug.,NaN,Discontinuation of the manufacture of the drug,NaN,NaN,NaN

In [26]:
# Check shape

shortage_df.shape

(1747, 19)

In [27]:
# Check the 'discontinued_date', 'initial_posting_date', and 'update_date' columns format
for c in ["discontinued_date", "initial_posting_date", "update_date"]:
    print("\n", c)
    print(shortage_df[c].dtype)
    print(shortage_df[c].head(10).tolist())
    print(shortage_df[c].astype("string").str.strip().value_counts(dropna=False).head(3))

 discontinued_date
object
[nan, nan, '11/07/2025', nan, nan, nan, nan, nan, nan, '06/03/2025']
discontinued_date
<NA>          1233
06/13/2025      35
07/10/2025      22
Name: count, dtype: Int64

 initial_posting_date
object
['10/12/2022', '03/23/2018', '11/07/2025', '02/03/2016', '04/28/2023', '03/10/2023', '07/14/2023', '03/13/2023', '07/26/2023', '06/03/2025']
initial_posting_date
07/14/2023    99
10/12/2022    72
02/20/2018    70
Name: count, dtype: Int64

 update_date
object
['02/02/2026', '02/05/2026', '11/07/2025', '12/22/2025', '01/15/2026', '02/03/2026', '12/09/2025', '02/05/2026', '02/02/2026', '06/03/2025']
update_date
02/05/2026    261
02/02/2026    204
01/23/2026    198
Name: count, dtype: Int64

In [28]:
# Convert date columns to ISO-8601 format for MySQL DATE compatibility
date_cols = ['discontinued_date', 'initial_posting_date', 'update_date']
for col in date_cols:
    dt = pd.to_datetime(shortage_df[col], format="%m/%d/%Y", errors="coerce")
    shortage_df[col] = dt.dt.strftime("%Y-%m-%d").astype("string")
# Verify date conversion
for c in date_cols:
    print("\n", c)
    print(shortage_df[c].dtype)
    print(shortage_df[c].head(10).tolist())
    print(shortage_df[c].value_counts(dropna=False).head(3))

 discontinued_date
string
[<NA>, <NA>, '2025-11-07', <NA>, <NA>, <NA>, <NA>, <NA>, <NA>, '2025-06-03']
discontinued_date
<NA>          1233
2025-06-13      35
2025-07-10      22
Name: count, dtype: Int64

 initial_posting_date
string
['2022-10-12', '2018-03-23', '2025-11-07', '2016-02-03', '2023-04-28', '2023-03-10', '2023-07-14', '2023-03-13', '2023-07-26', '2025-06-03']
initial_posting_date
2023-07-14    99
2022-10-12    72
2018-02-20    70
Name: count, dtype: Int64

 update_date
string
['2026-02-02', '2026-02-05', '2025-11-07', '2025-12-22', '2026-01-15', '2026-02-03', '2025-12-09', '2026-02-05', '2026-02-02', '2025-06-03']
update_date
2026-02-05    261
2026-02-02    204
2026-01-23    198
Name: count, dtype: Int64

In [29]:
# List columns

shortage_df.columns.tolist()

['update_type',
 'initial_posting_date',
 'package_ndc',
 'generic_name',
 'contact_info',
 'availability',
 'openfda',
 'update_date',
 'therapeutic_category',
 'dosage_form',
 'presentation',
 'company_name',
 'status',
 'related_info',
 'discontinued_date',
 'shortage_reason',
 'change_date',
 'related_info_link',
 'resolved_note']

In [30]:
# Create core drug shortage table for analysis and joining to NDC packaging

shortage_core_cols = [
    "package_ndc",
    "generic_name",
    "company_name",
    "status",
    "availability",
    "shortage_reason",
    "update_type",
    "initial_posting_date",
    "update_date",
    "discontinued_date",
    "change_date",
    "resolved_note",
    "therapeutic_category",
    "dosage_form",
    "presentation"
]

drug_shortages = shortage_df[shortage_core_cols].copy()

drug_shortages.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation
0,0555-0971-02,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,Available,NaN,Revised,2022-10-12,2026-02-02,<NA>,NaN,NaN,[Psychiatry],Tablet,"Dextroamphetamine Saccharate, Amphetamine Aspa..."
1,63323-285-61,Ropivacaine Hydrochloride Injection,"Fresenius Kabi USA, LLC",Current,Unavailable,NaN,Reverified,2018-03-23,2026-02-05,<NA>,NaN,NaN,[Anesthesia],Injection,"Naropin, Injection, 2 mg/1 mL (NDC 63323-285-61)"
2,0409-4911-34,Atropine Sulfate Injection,"Hospira, Inc., a Pfizer Company",To Be Discontinued,NaN,NaN,New,2025-11-07,2025-11-07,2025-11-07,NaN,NaN,"[Anesthesia, Neurology, Pediatric]",Injection,"Atropine Sulfate, Injection, (Adult)1 mg/10 mL..."
3,0641-6262-01,Sodium Acetate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Available,NaN,New,2016-02-03,2025-12-22,<NA>,NaN,NaN,"[Endocrinology/Metabolism, Gastroenterology, P...",Injection,"Sodium Acetate, Injection, 100 mEq/50mL (2 mEq..."
4,60505-6282-7,Carboplatin Injection,Teyro Labs,Current,Limited Availability,Discontinuation of the manufacture of the drug,Revised,2023-04-28,2026-01-15,<NA>,NaN,NaN,[Oncology],Injection,"Carboplatin, Injection, 600 mg/60 mL (10 mg/mL..."

In [31]:
# Preview the contact_info field to understand its structure before normalization

shortage_df["contact_info"].head(20)

0                  800-545-8800
1                  888-386-1300
2                  844-646-4398
3                  800-631-2174
4     Apotex Inc.: 800-706-5575
5        866-941-7875, option 2
6                  866-525-7270
7                  888-386-1300
8                  800-541-4802
9                  866-850-2876
10                 855-228-9470
11                 800-545-8800
12                 800-633-1610
13                 866-888-0660
14                 800-533-4535
15       866-941-7875, option 2
16                 888-386-1300
17                 844-646-4398
18                 866-850-2876
19                 800-631-2174
Name: contact_info, dtype: object

In [32]:
# Extract contact_info into a separate table keyed by package_ndc

shortage_contacts = (
    shortage_df[["package_ndc", "contact_info"]]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

shortage_contacts.head()

    package_ndc               contact_info
0  0555-0971-02               800-545-8800
1  63323-285-61               888-386-1300
2  0409-4911-34               844-646-4398
3  0641-6262-01               800-631-2174
4  60505-6282-7  Apotex Inc.: 800-706-5575

In [33]:
# Remove contact_info from the core shortages table after normalization

drug_shortages = drug_shortages.drop(columns=["contact_info"], errors="ignore")

drug_shortages.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation
0,0555-0971-02,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,Available,NaN,Revised,2022-10-12,2026-02-02,<NA>,NaN,NaN,[Psychiatry],Tablet,"Dextroamphetamine Saccharate, Amphetamine Aspa..."
1,63323-285-61,Ropivacaine Hydrochloride Injection,"Fresenius Kabi USA, LLC",Current,Unavailable,NaN,Reverified,2018-03-23,2026-02-05,<NA>,NaN,NaN,[Anesthesia],Injection,"Naropin, Injection, 2 mg/1 mL (NDC 63323-285-61)"
2,0409-4911-34,Atropine Sulfate Injection,"Hospira, Inc., a Pfizer Company",To Be Discontinued,NaN,NaN,New,2025-11-07,2025-11-07,2025-11-07,NaN,NaN,"[Anesthesia, Neurology, Pediatric]",Injection,"Atropine Sulfate, Injection, (Adult)1 mg/10 mL..."
3,0641-6262-01,Sodium Acetate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Available,NaN,New,2016-02-03,2025-12-22,<NA>,NaN,NaN,"[Endocrinology/Metabolism, Gastroenterology, P...",Injection,"Sodium Acetate, Injection, 100 mEq/50mL (2 mEq..."
4,60505-6282-7,Carboplatin Injection,Teyro Labs,Current,Limited Availability,Discontinuation of the manufacture of the drug,Revised,2023-04-28,2026-01-15,<NA>,NaN,NaN,[Oncology],Injection,"Carboplatin, Injection, 600 mg/60 mL (10 mg/mL..."

In [34]:
# Join drug shortages to NDC packaging on package_ndc

shortages_with_ndc = drug_shortages.merge(
    ndc_packaging,
    on="package_ndc",
    how="left"
)

shortages_with_ndc.head()

,package_ndc,generic_name,company_name,status,availability,shortage_reason,update_type,initial_posting_date,update_date,discontinued_date,change_date,resolved_note,therapeutic_category,dosage_form,presentation,product_ndc,description,marketing_start_date,marketing_end_date,sample
0,0555-0971-02,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,Available,NaN,Revised,2022-10-12,2026-02-02,<NA>,NaN,NaN,[Psychiatry],Tablet,"Dextroamphetamine Saccharate, Amphetamine Aspa...",0555-0971,100 TABLET in 1 BOTTLE (0555-0971-02),2002-02-11,<NA>,False
1,63323-285-61,Ropivacaine Hydrochloride Injection,"Fresenius Kabi USA, LLC",Current,Unavailable,NaN,Reverified,2018-03-23,2026-02-05,<NA>,NaN,NaN,[Anesthesia],Injection,"Naropin, Injection, 2 mg/1 mL (NDC 63323-285-61)",63323-285,24 BAG in 1 CASE (63323-285-61) / 100 mL in 1...,2011-05-31,<NA>,False
2,0409-4911-34,Atropine Sulfate Injection,"Hospira, Inc., a Pfizer Company",To Be Discontinued,NaN,NaN,New,2025-11-07,2025-11-07,2025-11-07,NaN,NaN,"[Anesthesia, Neurology, Pediatric]",Injection,"Atropine Sulfate, Injection, (Adult)1 mg/10 mL...",NaN,NaN,<NA>,<NA>,NaN
3,0641-6262-01,Sodium Acetate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,Available,NaN,New,2016-02-03,2025-12-22,<NA>,NaN,NaN,"[Endocrinology/Metabolism, Gastroenterology, P...",Injection,"Sodium Acetate, Injection, 100 mEq/50mL (2 mEq...",0641-6262,1 VIAL in 1 CARTON (0641-6262-01) / 50 mL in ...,2024-05-20,<NA>,False
4,60505-6282-7,Carboplatin Injection,Teyro Labs,Current,Limited Availability,Discontinuation of the manufacture of the drug,Revised,2023-04-28,2026-01-15,<NA>,NaN,NaN,[Oncology],Injection,"Carboplatin, Injection, 600 mg/60 mL (10 mg/mL...",60505-6282,"1 VIAL, MULTI-DOSE in 1 CARTON (60505-6282-7) ...",2024-01-10,<NA>,False

In [35]:
# Check how many shortage records successfully joined to NDC packaging

shortages_with_ndc["product_ndc"].isna().value_counts()

product_ndc
False    1575
True      172
Name: count, dtype: int64

In [36]:
# Inspect shortages that did not match NDC packaging

unmatched_shortages = shortages_with_ndc[shortages_with_ndc["product_ndc"].isna()]
unmatched_shortages[["package_ndc", "generic_name", "company_name"]].head()

,package_ndc,generic_name,company_name
2,0409-4911-34,Atropine Sulfate Injection,"Hospira, Inc., a Pfizer Company"
14,0071-0535-23,Quinapril Hydrochloride Tablet,Pfizer Inc.
22,0527-1502-37,"Amphetamine Aspartate Monohydrate, Amphetamine...","Lannett Company, Inc."
23,0187-5100-01,Pimecrolimus Cream,"Bausch Health Americas, Inc."
31,0409-4900-14,Sodium Bicarbonate Injection,"Hospira, Inc., a Pfizer Company"

In [37]:
# Confirm final analysis table shape after join

shortages_with_ndc.shape

(1747, 20)

In [38]:
# Save final analysis-ready tables

shortages_with_ndc.to_csv("data/shortages_with_ndc.csv", index=False)
drug_shortages.to_csv("data/drug_shortages_core.csv", index=False)
shortage_contacts.to_csv("data/shortage_contacts.csv", index=False)

# Begin analysis of FDA drug shortages using the final joined shortages + NDC dataset.

In [39]:
# Count shortages by status

shortages_with_ndc["status"].value_counts()

status
Current               1175
To Be Discontinued     516
Resolved                56
Name: count, dtype: int64

In [40]:
# Count shortages by therapeutic category

shortages_with_ndc["therapeutic_category"].value_counts().head(10)

therapeutic_category
[Psychiatry]                                                      254
[Anesthesia]                                                      232
[Cardiovascular]                                                  186
[Analgesia/Addiction]                                             129
[Endocrinology/Metabolism]                                         90
[Anti-Infective]                                                   74
[Anesthesia, Pediatric]                                            70
[Neurology]                                                        64
[Oncology]                                                         63
[Endocrinology/Metabolism, Gastroenterology, Other, Pediatric]     56
Name: count, dtype: int64

In [41]:
# Count shortages by dosage form

shortages_with_ndc["dosage_form"].value_counts().head(10)

dosage_form
Injection                    999
Tablet                       432
Capsule                      155
Capsule, Extended Release     21
Tablet, Chewable              19
Solution                      14
Powder                        10
Irrigant                       9
Cream                          8
Powder, For Solution           8
Name: count, dtype: int64

In [42]:
# Count shortages by manufacturer

shortages_with_ndc["company_name"].value_counts().head(10)

company_name
Hospira, Inc., a Pfizer Company    204
Fresenius Kabi USA, LLC            164
Teva Pharmaceuticals USA, Inc.     129
Hikma Pharmaceuticals USA, Inc.     96
Pfizer Inc.                         80
Upsher-Smith Laboratories, LLC      73
Baxter Healthcare                   70
Eugia US LLC                        48
Sandoz Inc.                         48
Aurobindo Pharma USA                37
Name: count, dtype: int64

In [43]:
# Status distribution for top manufacturers

top_manufacturers = shortages_with_ndc["company_name"].value_counts().head(10).index

shortages_with_ndc[
    shortages_with_ndc["company_name"].isin(top_manufacturers)
].groupby(["company_name", "status"]).size().unstack(fill_value=0)

status                           Current  Resolved  To Be Discontinued
company_name
Aurobindo Pharma USA                  19         0                  18
Baxter Healthcare                     62         7                   1
Eugia US LLC                          48         0                   0
Fresenius Kabi USA, LLC              157         0                   7
Hikma Pharmaceuticals USA, Inc.       92         3                   1
Hospira, Inc., a Pfizer Company      168         0                  36
Pfizer Inc.                           36        12                  32
Sandoz Inc.                           11         2                  35
Teva Pharmaceuticals USA, Inc.        44         1                  84
Upsher-Smith Laboratories, LLC         0         0                  73

In [44]:
# Calculate shortage duration using initial_posting_date and latest update_date

shortages_with_ndc["initial_posting_date"] = pd.to_datetime(
    shortages_with_ndc["initial_posting_date"], errors="coerce"
)

shortages_with_ndc["update_date"] = pd.to_datetime(
    shortages_with_ndc["update_date"], errors="coerce"
)

shortages_with_ndc["duration_days"] = (
    shortages_with_ndc["update_date"] - shortages_with_ndc["initial_posting_date"]
).dt.days

shortages_with_ndc["duration_days"].describe()

count    1747.000000
mean     1357.878077
std      1323.049599
min         0.000000
25%         0.000000
50%      1036.000000
75%      2127.000000
max      5149.000000
Name: duration_days, dtype: float64

# Relational analysis begins here: insights derived from the joined drug shortages + NDC packaging dataset

In [45]:
# Analyze package-level shortages with identifying drug, manufacturer, and packaging details

# Create a package-level shortage view with key identifying fields

package_shortage_view = shortages_with_ndc[
    [
        "generic_name",
        "company_name",
        "status",
        "description",
        "product_ndc",
        "package_ndc"
    ]
].drop_duplicates()

package_shortage_view.head(10)

,generic_name,company_name,status,description,product_ndc,package_ndc
0,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,100 TABLET in 1 BOTTLE (0555-0971-02),0555-0971,0555-0971-02
1,Ropivacaine Hydrochloride Injection,"Fresenius Kabi USA, LLC",Current,24 BAG in 1 CASE (63323-285-61) / 100 mL in 1...,63323-285,63323-285-61
2,Atropine Sulfate Injection,"Hospira, Inc., a Pfizer Company",To Be Discontinued,NaN,NaN,0409-4911-34
3,Sodium Acetate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,1 VIAL in 1 CARTON (0641-6262-01) / 50 mL in ...,0641-6262,0641-6262-01
4,Carboplatin Injection,Teyro Labs,Current,"1 VIAL, MULTI-DOSE in 1 CARTON (60505-6282-7) ...",60505-6282,60505-6282-7
5,Clonazepam Tablet,Accord Healthcare Inc.,Current,"100 TABLET in 1 BOTTLE, PLASTIC (16729-136-00)",16729-136,16729-136-00
6,Lisdexamfetamine Dimesylate Capsule,Amneal Pharmaceuticals,Current,90 CAPSULE in 1 BOTTLE (65162-026-09),65162-026,65162-026-09
7,Methotrexate Sodium Injection,"Fresenius Kabi USA, LLC",Current,1 VIAL in 1 CARTON (63323-122-50) / 1 INJECTI...,63323-122,63323-122-50
8,"Methylphenidate Hydrochloride Tablet, Extended...","Vertical Pharmaceuticals, LLC",Current,"30 TABLET, EXTENDED RELEASE in 1 BOTTLE (68025...",68025-084,68025-084-30
9,Metoprolol Tartrate Tablet,Aurobindo Pharma USA,To Be Discontinued,"5000 TABLET, FILM COATED in 1 BAG (65862-063-59)",65862-063,65862-063-59

In [46]:
# Focus on current shortages at the package level

current_package_shortages = package_shortage_view[
    package_shortage_view["status"] == "Current"
]

current_package_shortages.head(10)

,generic_name,company_name,status,description,product_ndc,package_ndc
0,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,100 TABLET in 1 BOTTLE (0555-0971-02),0555-0971,0555-0971-02
1,Ropivacaine Hydrochloride Injection,"Fresenius Kabi USA, LLC",Current,24 BAG in 1 CASE (63323-285-61) / 100 mL in 1...,63323-285,63323-285-61
3,Sodium Acetate Injection,"Hikma Pharmaceuticals USA, Inc.",Current,1 VIAL in 1 CARTON (0641-6262-01) / 50 mL in ...,0641-6262,0641-6262-01
4,Carboplatin Injection,Teyro Labs,Current,"1 VIAL, MULTI-DOSE in 1 CARTON (60505-6282-7) ...",60505-6282,60505-6282-7
5,Clonazepam Tablet,Accord Healthcare Inc.,Current,"100 TABLET in 1 BOTTLE, PLASTIC (16729-136-00)",16729-136,16729-136-00
6,Lisdexamfetamine Dimesylate Capsule,Amneal Pharmaceuticals,Current,90 CAPSULE in 1 BOTTLE (65162-026-09),65162-026,65162-026-09
7,Methotrexate Sodium Injection,"Fresenius Kabi USA, LLC",Current,1 VIAL in 1 CARTON (63323-122-50) / 1 INJECTI...,63323-122,63323-122-50
8,"Methylphenidate Hydrochloride Tablet, Extended...","Vertical Pharmaceuticals, LLC",Current,"30 TABLET, EXTENDED RELEASE in 1 BOTTLE (68025...",68025-084,68025-084-30
10,Midazolam Hydrochloride Injection,"Avet Pharmaceuticals, Inc.",Current,"25 VIAL, SINGLE-DOSE in 1 CARTON (23155-600-41...",23155-600,23155-600-41
11,"Amphetamine Aspartate Monohydrate, Amphetamine...","Teva Pharmaceuticals USA, Inc.",Current,100 TABLET in 1 BOTTLE (57844-112-01),57844-112,57844-112-01

In [47]:
# Identify products with shortages affecting multiple package configurations

# Count number of affected packages per product

product_package_counts = (
    shortages_with_ndc
    .groupby(["product_ndc", "generic_name"])
    .agg(
        affected_packages=("package_ndc", "nunique"),
        manufacturer=("company_name", "first")
    )
    .reset_index()
)

# Focus on products with more than one affected package
multi_package_shortages = product_package_counts[
    product_package_counts["affected_packages"] > 1
].sort_values("affected_packages", ascending=False)

multi_package_shortages.head(10)

,product_ndc,generic_name,affected_packages,manufacturer
180,0338-0017,Dextrose Monohydrate 5% Injection,9,Baxter Healthcare
917,63323-285,Ropivacaine Hydrochloride Injection,8,"Fresenius Kabi USA, LLC"
918,63323-286,Ropivacaine Hydrochloride Injection,6,"Fresenius Kabi USA, LLC"
346,0409-6102,Furosemide Injection,6,"Hospira, Inc., a Pfizer Company"
563,0990-7922,Dextrose Monohydrate 5% Injection,5,Otsuka ICU Medical LLC
564,0990-7923,Dextrose Monohydrate 5% Injection,5,Otsuka ICU Medical LLC
967,63323-806,Fentanyl Citrate Injection,5,"Fresenius Kabi USA, LLC"
368,0409-9094,Fentanyl Citrate Injection,5,"Hospira, Inc., a Pfizer Company"
869,61703-339,Carboplatin Injection,4,"Hospira, Inc., a Pfizer Company"
920,63323-288,Ropivacaine Hydrochloride Injection,4,"Fresenius Kabi USA, LLC"

In [48]:
# Assess manufacturer exposure based on the number of affected package configurations

# Count distinct affected packages per manufacturer

manufacturer_package_exposure = (
    shortages_with_ndc
    .groupby("company_name")
    .agg(
        affected_packages=("package_ndc", "nunique"),
        affected_products=("product_ndc", "nunique")
    )
    .reset_index()
    .sort_values("affected_packages", ascending=False)
)

manufacturer_package_exposure.head(10)

                        company_name  affected_packages  affected_products
57   Hospira, Inc., a Pfizer Company                194                120
45           Fresenius Kabi USA, LLC                164                 96
124   Teva Pharmaceuticals USA, Inc.                126                 91
56   Hikma Pharmaceuticals USA, Inc.                 96                 89
98                       Pfizer Inc.                 80                 59
128   Upsher-Smith Laboratories, LLC                 73                 38
22                 Baxter Healthcare                 70                 41
41                      Eugia US LLC                 48                 48
109                      Sandoz Inc.                 48                 33
16              Aurobindo Pharma USA                 36                 24

In [49]:
# Identify manufacturers with the highest number of currently active package-level shortages

# Focus on current shortages only
current_shortages = shortages_with_ndc[
    shortages_with_ndc["status"] == "Current"
]

# Count active affected packages per manufacturer
current_manufacturer_risk = (
    current_shortages
    .groupby("company_name")
    .agg(
        current_affected_packages=("package_ndc", "nunique"),
        current_affected_products=("product_ndc", "nunique")
    )
    .reset_index()
    .sort_values("current_affected_packages", ascending=False)
)

current_manufacturer_risk.head(10)

,company_name,current_affected_packages,current_affected_products
38,"Hospira, Inc., a Pfizer Company",168,102
31,"Fresenius Kabi USA, LLC",157,91
37,"Hikma Pharmaceuticals USA, Inc.",92,86
14,Baxter Healthcare,62,36
27,Eugia US LLC,48,48
87,"Teva Pharmaceuticals USA, Inc.",44,40
67,Pfizer Inc.,36,27
0,Accord Healthcare Inc.,26,14
63,Otsuka ICU Medical LLC,24,12
32,Gland Pharma Limited,24,13